CU/10042-rachael-detox-change-send-to-testRail-job
department-of-veterans-affairs/va-mobile-app pull request #10043
Opened 2024-10-25 20:21 UTC by rbontrager

## Description of Change

## Screenshots/Video

## Testing

- [ ] Tested on iOS 
- [ ] Tested on Android 

## Reviewer Validations

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2024-10-29 13:19 UTC, rbontrager commented
@TKDickson I'm running the final tests on ios but this should be fixed.

2024-10-29 13:19 UTC, TKDickson requested changes
Requesting changes on Rachael's behalf: failing the change send to testRail job PR because the upload-junit occasionally doesn't upload anything I need to figure out a way to get and run only the uploaded files (and not just try to say hey you ran 3 tests so we are going to call this 3 times).

2024-10-29 15:06 UTC, TKDickson commented
Similar scenario with my iOS test run ([github](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11575354981), [testrail](https://dsvavsp.testrail.io/index.php?/runs/view/6169&group_by=cases:section_id&group_order=asc)) where many cases ran (all the fails maybe?) didn't come over. Android 'all tests' worked well ([github](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11575350105), [testrail](https://dsvavsp.testrail.io/index.php?/runs/view/6168&group_by=cases:section_id&group_order=asc)), going to run some one-off selections with Android.

2024-10-30 15:05 UTC, TKDickson approved these changes

2024-11-05 16:27 UTC, timwright12 approved these changes

2024-11-05 16:38 UTC, merged