Feature/9971 e folder view analytics
department-of-veterans-affairs/va-mobile-app pull request #10067
Opened 2024-10-30 19:35 UTC by Sparowhawk

## Description of Change
Added analytics for e folder file view

## Screenshots/Video
N/A

## Testing
yarn test

- [x] Tested on iOS 
- [x] Tested on Android 

## Reviewer Validations
 Include new Analytic for claim file review.

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [x] PR is connected to issue(s)
- [x] Tests are included to cover this change (when possible)
- [x] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [x] No secrets or API keys are checked in
- [x] All imports are absolute (no relative imports)
- [x] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2024-11-07 15:25 UTC, dumathane requested changes
please change target merge branch to isolate only these tickets changes.

2024-11-07 19:01 UTC, Sparowhawk commented
> please change target merge branch to isolate only these tickets changes.

updated

2024-11-19 18:14 UTC, rbontrager approved these changes

2024-11-19 20:52 UTC, rbontrager approved these changes

2024-11-19 21:15 UTC, dumathane approved these changes

2024-11-19 22:28 UTC, merged