CU-10121-add-sarah-uber-to-release-coordination-thread
department-of-veterans-affairs/va-mobile-app pull request #10122
Opened 2024-11-06 17:29 UTC by IsraelleHub

## Description of Change
As part of maintaining the [release_branch_issue workflow](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/.github/workflows/release_branch_issue.yml). We need to changes the release manager, from Kelly to Sarah.
Sarah Slack ID: U07U9EDGAFP: slack id
Sarah Github username: SarahHuber-AdHoc

## Screenshots/Video

## Testing

- [ ] Tested on iOS 
- [ ] Tested on Android 

## Reviewer Validations

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2024-11-06 17:38 UTC, TKDickson commented
Want to just update this to include the full scope of [9828](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9828)?

2024-11-06 17:58 UTC, timwright12 submitted a review, later dismissed

2024-11-06 18:40 UTC, TKDickson requested changes
whoops, meant to request changes with my earlier comment

2024-11-06 19:41 UTC, TKDickson approved these changes

2024-11-07 19:40 UTC, timwright12 approved these changes

2024-11-07 20:01 UTC, merged