chore/9995-Usei18nInUnitTests-Home-3
department-of-veterans-affairs/va-mobile-app pull request #10157
Opened 2024-11-12 14:58 UTC by ATeal

## Description of Change
Update the unit test in [this issue](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9995) to use i18n.

## Screenshots/Video

## Testing

- [ ] Tested on iOS 
- [ ] Tested on Android 

## Reviewer Validations

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [x] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2024-11-12 19:05 UTC, dumathane commented on VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/IncorrectServiceInfo/IncorrectServiceInfo.test.tsx
> +    fireEvent.press(screen.getByRole('link', { name: displayedTextPhoneNumber(i18nPhoneNumber) }))
No need for the const, you can just pass t('800... here.

2024-11-12 19:06 UTC, dumathane commented on VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/IncorrectServiceInfo/IncorrectServiceInfo.test.tsx
> +    fireEvent.press(screen.getByRole('link', { name: displayedTextPhoneNumber(i18nPhoneNumber) }))
```suggestion
    fireEvent.press(screen.getByRole('link', { name: displayedTextPhoneNumber(t('8005389552') }))
```

2024-11-12 19:06 UTC, dumathane commented on VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/IncorrectServiceInfo/IncorrectServiceInfo.test.tsx
> +    const i18nPhoneNumber = t('8005389552')
```suggestion
```

2024-11-12 19:07 UTC, dumathane commented on VAMobile/src/screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/IncorrectServiceInfo/IncorrectServiceInfo.test.tsx
> +    expect(Linking.openURL).toHaveBeenCalledWith(`tel:${i18nPhoneNumber}`)
```suggestion
    expect(Linking.openURL).toHaveBeenCalledWith(`tel:${t('8005389552')}`)
```

2024-11-12 19:08 UTC, dumathane requested changes
Please drop the const declaration, otherwise this looks good.

2024-11-12 20:10 UTC, ATeal commented
> Please drop the const declaration, otherwise this looks good.

I went ahead and made the change. I originally had it that way but abstracted to avoid calling the `t(` function multiple times for the same string value. Nevertheless it's in :)

2024-11-13 16:36 UTC, rbontrager approved these changes

2024-11-14 15:50 UTC, merged