finished
department-of-veterans-affairs/va-mobile-app pull request #6462
Opened 2023-08-08 17:15 UTC by Sparowhawk

## Description of Change
Changed notched background for Splash Screen, Login Screen, and Login/Logout message screens to match Onboarding and be all blue

## Screenshots/Video
Toggle: <details><summary>Before/after:</summary><img src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/87150991/19b524d9-7aaf-440a-a586-04b44f83c21e" width="49%" />&nbsp;&nbsp;<img src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/87150991/8a33b725-9e99-4ab2-b477-63488b2950b0" width="49%" /></details>

https://github.com/department-of-veterans-affairs/va-mobile-app/assets/87150991/7fa3cafe-0fd5-4445-96e4-a5e827dca261

## Testing
yarn test

- [x] Tested on iOS 
- [x] Tested on Android 

## Reviewer Validations
Confirmed with Lauren that we'd want:

All-blue on the sign-in and sign-out loading screens
Red (for the VCL) and blue (for the rest of the screen) if we can make that happen on the prelogin home screen. If it's a hassle, then all-blue for that one too.

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [x] PR is connected to issue(s)
- [x] Tests are included to cover this change (when possible)
- [x] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [x] No secrets or API keys are checked in
- [x] All imports are absolute (no relative imports)
- [x] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2023-08-09 04:18 UTC, theodur requested changes
We have the [useOrientation](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/7eb0e875104139182d470bccf0f5edc642f9fa78/VAMobile/src/utils/hooks/index.tsx#L477-L497) hook that can be used to determine if the screen is portrait

2023-08-11 00:43 UTC, alexandec approved these changes

2023-08-11 01:17 UTC, theodur approved these changes

2023-08-14 22:57 UTC, DJUltraTom submitted a review, later dismissed

2023-08-15 13:28 UTC, Sparowhawk commented
@DJUltraTom @theodur @alexandec can you reapprove so we can get this merged? I had to fix a merge conflict. Thanks

2023-08-15 13:37 UTC, alexandec approved these changes

2023-08-15 21:37 UTC, theodur approved these changes

2023-08-15 22:32 UTC, DJUltraTom approved these changes

2023-08-16 13:31 UTC, merged