feature/5669-theo-dependabot
department-of-veterans-affairs/va-mobile-app pull request #6993
Opened 2023-10-13 04:33 UTC by theodur

## Description of Change

## Screenshots/Video

## Testing

- [ ] Tested on iOS 
- [ ] Tested on Android 

## Reviewer Validations

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2023-10-19 16:23 UTC, alexandec submitted a review, later dismissed

2023-10-20 18:08 UTC, Sparowhawk requested changes
add the same push on the e2e_android.yml file and I will approve

2023-10-23 22:05 UTC, theodur commented
> add the same push on the e2e_android.yml file and I will approve

@Sparowhawk It looks like that workflow was added after this PR was created, which is why that workflow wasn't updated. I merged the latest `develop` and updated that trigger to it. We should be good now

2023-10-24 15:42 UTC, alexandec approved these changes

2023-10-25 04:53 UTC, Sparowhawk approved these changes

2023-10-25 18:47 UTC, merged