PaymentsAndDirectDeposit
department-of-veterans-affairs/va-mobile-app pull request #7132
Opened 2023-10-25 17:26 UTC by Sparowhawk

## Description of Change
Payments and Direct Deposit Unit Tests

## Screenshots/Video
N/A

## Testing
Yarn test

- [x] Tested on iOS 
- [x] Tested on Android 

## Reviewer Validations
S src/screens/PaymentsScreen/PaymentHistory/PaymentIssueScreen/PaymentIssueScreen.test.tsx
S src/screens/PaymentsScreen/PaymentHistory/NoPayments/NoPaymentsScreen.test.tsx
M src/screens/PaymentsScreen/PaymentHistory/PaymentHistoryScreen.test.tsx
S src/screens/PaymentsScreen/PaymentHistory/PaymentDetailsScreen/PaymentDetailsScreen.test.tsx
S src/screens/PaymentsScreen/PaymentHistory/PaymentMissingSceen/PaymentMissingScreen.test.tsx
M src/screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen.test.tsx
S src/screens/PaymentsScreen/DirectDepositScreen/HowToUpdateDirectDepositScreen/HowToUpdateDirectDepositScreen.test.tsx

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [x] PR is connected to issue(s)
- [x] Tests are included to cover this change (when possible)
- [x] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [x] No secrets or API keys are checked in
- [x] All imports are absolute (no relative imports)
- [x] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2023-10-31 16:12 UTC, theodur requested changes
[This comment](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7148#pullrequestreview-1706588458) applies to this PR also

2023-11-02 04:29 UTC, Sparowhawk commented
> [This comment](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7148#pullrequestreview-1706588458) applies to this PR also

updated. Note some buttons/links could not be access with getByRole method due to duplicate roles having the same name on some screens and others having multiple textviews so you couldn't get it by the name method or the other options from get by role.

2023-11-08 18:06 UTC, theodur requested changes

2023-11-08 18:49 UTC, Sparowhawk commented on VAMobile/src/screens/PaymentsScreen/PaymentsScreen.test.tsx
>      it('should navigate to HowToUpdateDirectDeposit', async () => {
updated

2023-11-08 18:49 UTC, Sparowhawk commented on VAMobile/src/screens/PaymentsScreen/PaymentsScreen.test.tsx
>      it('should navigate to DirectDeposit', async () => {
updated

2023-11-08 18:49 UTC, Sparowhawk commented on VAMobile/src/screens/PaymentsScreen/PaymentsScreen.test.tsx
>      it('should navigate to PaymentHistory', async () => {
updated

2023-11-08 18:51 UTC, Sparowhawk commented on VAMobile/src/screens/PaymentsScreen/PaymentsScreen.test.tsx
>        fireEvent.press(screen.getByText('VA payment history'))
updated

2023-11-08 18:51 UTC, Sparowhawk commented on VAMobile/src/screens/PaymentsScreen/PaymentsScreen.test.tsx
>        fireEvent.press(screen.getByText('Direct deposit information'))
updated

2023-11-08 18:51 UTC, Sparowhawk commented on VAMobile/src/screens/PaymentsScreen/PaymentsScreen.test.tsx
>        fireEvent.press(screen.getByText('Direct deposit information'))
updated

2023-11-08 18:51 UTC, Sparowhawk commented on VAMobile/src/screens/PaymentsScreen/PaymentsScreen.test.tsx
> +import { fireEvent, screen } from '@testing-library/react-native'
updated

2023-11-15 16:20 UTC, alexandec approved these changes

2023-11-15 20:36 UTC, theodur approved these changes

2023-11-15 20:43 UTC, merged