finished
department-of-veterans-affairs/va-mobile-app pull request #7133
Opened 2023-10-25 17:37 UTC by Sparowhawk

## Description of Change
Login and Webview screens

## Screenshots/Video
N/A

## Testing
yarn test

- [x] Tested on iOS 
- [x] Tested on Android 

## Reviewer Validations
S src/App.test.tsx
S src/screens/BiometricsPreferenceScreen/BiometricsPreferenceScreen.test.tsx
S src/screens/auth/LoaGate/LoaGate.test.tsx
S src/screens/auth/LoginScreen/LoginScreen.test.tsx
S src/screens/WebviewScreen/WebviewControlButton.test.tsx
S src/screens/WebviewScreen/WebviewControls.test.tsx
S src/screens/WebviewScreen/WebviewTitle.test.tsx
S src/screens/WebviewScreen/WebviewScreen.test.tsx

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [x] PR is connected to issue(s)
- [x] Tests are included to cover this change (when possible)
- [x] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [x] No secrets or API keys are checked in
- [x] All imports are absolute (no relative imports)
- [x] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2023-10-31 16:31 UTC, theodur requested changes
Seeing the same issues in this PR also
https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7148#pullrequestreview-1706588458

2023-11-02 04:52 UTC, Sparowhawk commented
> Seeing the same issues in this PR also [#7148 (review)](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7148#pullrequestreview-1706588458)

updated

2023-11-21 03:15 UTC, theodur requested changes

2023-11-21 03:15 UTC, theodur commented on VAMobile/src/screens/auth/LoaGate/LoaGate.test.tsx
> +    expect(screen.getByText('Sign in')).toBeTruthy()
```suggestion
    expect(screen.getByRole('header', { name: 'Sign in' })).toBeTruthy()
```

2023-11-21 03:15 UTC, theodur commented on VAMobile/src/screens/auth/LoaGate/LoaGate.test.tsx
> +    expect(screen.getByText("Read more if you haven't yet verified")).toBeTruthy()
```suggestion
    expect(screen.getByRole('tab', { name: "Read more if you haven't yet verified" })).toBeTruthy()
```

2023-11-21 15:48 UTC, Sparowhawk commented on VAMobile/src/screens/auth/LoaGate/LoaGate.test.tsx
> +    expect(screen.getByText('Sign in')).toBeTruthy()
updated

2023-11-21 18:10 UTC, alexandec approved these changes

2023-11-21 19:49 UTC, merged