finished
department-of-veterans-affairs/va-mobile-app pull request #7145
Opened 2023-10-25 20:26 UTC by Sparowhawk

## Description of Change
Appointment Details Unit Tests

## Screenshots/Video
N/A

## Testing
Yarn Test

- [x] Tested on iOS 
- [x] Tested on Android 

## Reviewer Validations
S src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/ContactInformation.test.tsx
M src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/ProviderName.test.tsx
S src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PreferredAppointmentType.test.tsx
S src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PreferredDateAndTime.test.tsx
S src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentTypeAndDate.test.tsx
S src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentReason.test.tsx
M src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentAlert.test.tsx
S src/screens/HealthScreen/Appointments/AppointmentDetailsCommon/PendingAppointmentCancelButton.test.tsx

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [x] PR is connected to issue(s)
- [x] Tests are included to cover this change (when possible)
- [x] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [x] No secrets or API keys are checked in
- [x] All imports are absolute (no relative imports)
- [x] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2023-10-31 16:34 UTC, theodur requested changes
Same issues here
https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7148#pullrequestreview-1706588458

2023-11-02 21:04 UTC, Sparowhawk commented
> Same issues here [#7148 (review)](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7148#pullrequestreview-1706588458)

updated

2023-11-16 22:41 UTC, alexandec approved these changes

2023-11-17 16:05 UTC, dumathane approved these changes

2023-11-20 17:57 UTC, theodur approved these changes

2023-11-21 14:46 UTC, merged