finished
department-of-veterans-affairs/va-mobile-app pull request #7148
Opened 2023-10-25 21:09 UTC by Sparowhawk

## Description of Change
Appeals Unit tests

## Screenshots/Video
N/A

## Testing
yarn test

- [x] Tested on iOS 
- [x] Tested on Android 

## Reviewer Validations
S src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealIssues/AppealIssues.test.tsx
L src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealDecision/AppealDecision.test.tsx
S src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealStatus.test.tsx
S src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealTimeline/AppealTimeline.test.tsx
S src/screens/BenefitsScreen/ClaimsScreen/NoClaimsAndAppeals/NoClaimsAndAppeals.test.tsx
L src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealTimeline/AppealPhase.test.tsx
L src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
M src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.test.tsx

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [x] PR is connected to issue(s)
- [x] Tests are included to cover this change (when possible)
- [x] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [x] No secrets or API keys are checked in
- [x] All imports are absolute (no relative imports)
- [x] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2023-10-31 15:17 UTC, theodur requested changes
I'm noticing a lot of the same things as in the [claims unit test PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7149#pullrequestreview-1698679906):
- `react-native` imports that can be removed
- `async` declarations that can be removed
- `getByText` queries that can be replaced with `getByRole`
- External node modules being grouped with relative imports

I would go through each file in this PR and address those issues

2023-11-02 06:26 UTC, Sparowhawk commented
> I'm noticing a lot of the same things as in the [claims unit test PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7149#pullrequestreview-1698679906):
> 
> * `react-native` imports that can be removed
> * `async` declarations that can be removed
> * `getByText` queries that can be replaced with `getByRole`
> * External node modules being grouped with relative imports
> 
> I would go through each file in this PR and address those issues

updated

2023-11-08 16:57 UTC, theodur requested changes
I'm still seeing places where `async` can be removed and `getByRole` can be used. You'll probably want to take another look at these files in this PR

2023-11-08 17:03 UTC, Sparowhawk commented
> I'm still seeing places where `async` can be removed and `getByRole` can be used. You'll probably want to take another look at these files in this PR

Actually the one screen that still has async and waitFor's is the AppealsDetailsScreen and those are necessary. Also the getByRoles you are referencing are not possible due to how the component is constructed in most cases.

It has a <textview> half the text </textview> <textview> half the text </textview> so get by role does not work

2023-11-08 19:53 UTC, theodur requested changes
I added suggestions and comments in the places I was referring in this [comment](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7148#pullrequestreview-1720845459)

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Board made a decision on your appeal')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'The Board made a decision on your appeal' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Board made a decision on your appeal')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'The Board made a decision on your appeal' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Veterans Benefits Administration granted your appeal')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'The Veterans Benefits Administration granted your appeal' })).toBeTruthy()})).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('You withdrew your appeal')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'You withdrew your appeal' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Your appeal was closed')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'Your appeal was closed' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('You opted in to the Rapid Appeals Modernization Program (RAMP)')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'You opted in to the Rapid Appeals Modernization Program (RAMP)' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The appeal was closed')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'The appeal was closed' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Your Motion for Reconsideration was denied')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'Your Motion for Reconsideration was denied' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Your appeal was closed')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'Your appeal was closed' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Please review your Supplemental Statement of the Case')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'Please review your Supplemental Statement of the Case' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Your appeal was merged')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'Your appeal was merged' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('You requested a decision review under the Appeals Modernization Act')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'You requested a decision review under the Appeals Modernization Act' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Your appeals file is open for new evidence')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'Your appeals file is open for new evidence' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Veterans Benefits Administration corrected an error')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'The Veterans Benefits Administration corrected an error' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Veterans Benefits Administration corrected an error')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'The Veterans Benefits Administration corrected an error' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('A reviewer is examining your new evidence')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'A reviewer is examining your new evidence' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Veterans Benefits Administration made a decision')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'The Veterans Benefits Administration made a decision' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Your Supplemental Claim was closed')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'Your Supplemental Claim was closed' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('A higher-level reviewer is taking a new look at your case')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'A higher-level reviewer is taking a new look at your case' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Veterans Benefits Administration made a decision')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'The Veterans Benefits Administration made a decision' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Veterans Benefits Administration is correcting an error')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'The Veterans Benefits Administration is correcting an error' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Your Higher-Level Review was closed')).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: 'Your Higher-Level Review was closed' })).toBeTruthy()
```

2023-11-08 19:53 UTC, theodur commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText("Your appeal was returned to the Board of Veterans' Appeals")).toBeTruthy()
```suggestion
      expect(screen.getByRole('header', { name: "Your appeal was returned to the Board of Veterans' Appeals" })).toBeTruthy()
```

2023-11-09 14:22 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.test.tsx
>      it('should show loading screen', async () => {
updated

2023-11-09 14:23 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.test.tsx
updated

2023-11-09 14:23 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.test.tsx
> +      expect(screen.getByText('Visit VA.gov')).toBeTruthy()
updated

2023-11-09 14:24 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.test.tsx
> +      expect(screen.getByText('Appeal for compensation')).toBeTruthy()
updated

2023-11-09 14:25 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.test.tsx
> +      await waitFor(async () => {
updated

2023-11-09 14:25 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.test.tsx
> +      expect(screen.getByText('Appeal for compensation')).toBeTruthy()
updated

2023-11-09 14:26 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.test.tsx
> +      expect(screen.getByText('Appeal for compensation')).toBeTruthy()
updated

2023-11-09 14:27 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealDetailsScreen.test.tsx
> +      expect(screen.getByText("The app can't be loaded.")).toBeTruthy()
updated

2023-11-09 14:28 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Please review your Statement of the Case')).toBeTruthy()
updated

2023-11-09 14:28 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Please review your Supplemental Statement of the Case')).toBeTruthy()
updated

2023-11-09 14:29 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +        expect(screen.getByText('Your appeal is waiting to be sent to a judge')).toBeTruthy()
updated

2023-11-09 14:29 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +        expect(screen.getByText("You're waiting for your hearing to be scheduled")).toBeTruthy()
updated

2023-11-09 14:29 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText("You're waiting for your hearing to be scheduled")).toBeTruthy()
updated

2023-11-09 14:30 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('A Decision Review Officer is reviewing your appeal')).toBeTruthy()
updated

2023-11-09 14:30 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +        expect(screen.getByText('A Decision Review Officer is reviewing your appeal')).toBeTruthy()
updated

2023-11-09 14:31 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Your appeal is with your Veterans Service Organization')).toBeTruthy()
updated

2023-11-09 14:31 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The judge is seeking more information before making a decision')).toBeTruthy()
updated

2023-11-09 14:31 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('A judge is reviewing your appeal')).toBeTruthy()
updated

2023-11-09 14:31 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +        expect(screen.getByText('A judge is reviewing your appeal')).toBeTruthy()
updated

2023-11-09 14:32 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Board made a decision on your appeal')).toBeTruthy()
updated

2023-11-09 14:32 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Board made a decision on your appeal')).toBeTruthy()
updated

2023-11-09 14:33 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Veterans Benefits Administration granted your appeal')).toBeTruthy()
updated

2023-11-09 14:36 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('You withdrew your appeal')).toBeTruthy()
updated

2023-11-09 14:36 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Your appeal was closed')).toBeTruthy()
updated

2023-11-09 14:36 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('You opted in to the Rapid Appeals Modernization Program (RAMP)')).toBeTruthy()
updated

2023-11-09 14:37 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The appeal was closed')).toBeTruthy()
updated

2023-11-09 14:37 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Your Motion for Reconsideration was denied')).toBeTruthy()
updated

2023-11-09 14:37 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Your appeal was closed')).toBeTruthy()
updated

2023-11-09 14:38 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Please review your Supplemental Statement of the Case')).toBeTruthy()
updated

2023-11-09 14:38 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Your appeal was merged')).toBeTruthy()
updated

2023-11-09 14:38 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('You requested a decision review under the Appeals Modernization Act')).toBeTruthy()
updated

2023-11-09 14:39 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Your appeals file is open for new evidence')).toBeTruthy()
updated

2023-11-09 14:39 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Veterans Benefits Administration corrected an error')).toBeTruthy()
updated

2023-11-09 14:39 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Veterans Benefits Administration corrected an error')).toBeTruthy()
updated

2023-11-09 14:40 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('A reviewer is examining your new evidence')).toBeTruthy()
updated

2023-11-09 14:40 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Veterans Benefits Administration made a decision')).toBeTruthy()
updated

2023-11-09 14:40 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Your Supplemental Claim was closed')).toBeTruthy()
updated

2023-11-09 14:40 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('A higher-level reviewer is taking a new look at your case')).toBeTruthy()
updated

2023-11-09 14:41 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Veterans Benefits Administration is correcting an error')).toBeTruthy()
updated

2023-11-09 14:41 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('The Veterans Benefits Administration made a decision')).toBeTruthy()
updated

2023-11-09 14:41 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText('Your Higher-Level Review was closed')).toBeTruthy()
updated

2023-11-09 14:42 UTC, Sparowhawk commented on VAMobile/src/screens/BenefitsScreen/ClaimsScreen/AppealDetailsScreen/AppealStatus/AppealCurrentStatus/AppealCurrentStatus.test.tsx
> +      expect(screen.getByText("Your appeal was returned to the Board of Veterans' Appeals")).toBeTruthy()
updated

2023-11-16 16:16 UTC, theodur approved these changes

2023-11-16 16:30 UTC, alexandec approved these changes

2023-11-16 16:48 UTC, merged