CU/7278-Chika-ReplaceWaygateNativeAlertFunctionWithCombo
department-of-veterans-affairs/va-mobile-app pull request #7589
Opened 2023-12-19 19:36 UTC by cadibemma

## Description of Change
- Update navigateTo() to reduce lines of code, simplify navigation and rope in waygate checks automatically.

## Screenshots/Video
- No UI Changes

## Testing

- [x] Tested on iOS 
- [x] Tested on Android 

## Reviewer Validations

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2023-12-19 21:14 UTC, alexandec commented
@cadibemma some conflicts to resolve on this one. Maybe it's related to the merge of the availability framework branch into develop?

2023-12-19 23:58 UTC, cadibemma commented
> @cadibemma some conflicts to resolve on this one. Maybe it's related to the merge of the availability framework branch into develop?

yup! I'm working on it

2023-12-20 23:13 UTC, alexandec requested changes
Nice work! Added a few minor suggestions, but fundamentally this looks good

2023-12-20 23:13 UTC, alexandec commented on VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PersonalInformationScreen.tsx
>    const onGenderIdentity = () => {
Probably no need for separate functions here anymore

2023-12-20 23:13 UTC, alexandec commented on VAMobile/src/screens/HomeScreen/ProfileScreen/ProfileScreen.tsx
>    const onPersonalInformation = () => {
Same thing with these separate functions

2023-12-20 23:13 UTC, alexandec commented on VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/SettingsScreen.tsx
>    const onManage = () => {
Same for these separate functions

2023-12-22 18:38 UTC, cadibemma commented on VAMobile/src/screens/PaymentsScreen/PaymentsScreen.test.tsx
> +      expect(mockNavigationSpy).toHaveBeenCalled()
updated!

2023-12-22 18:43 UTC, cadibemma commented on VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
> +    return navigation.navigate('PrescriptionDetails', { prescriptionId: prescriptionID })
Updated everywhere except within CarouselTabBar. When I updated there it breaks the `'renders correctly through out each screen and calls completeFirstTimeLogin once you get to the end'` test in the OnboardingCarousel test file.

2024-01-02 18:19 UTC, alexandec commented on VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
> +    return navigation.navigate('PrescriptionDetails', { prescriptionId: prescriptionID })
Ah I see, that test expects navigation to actually happen between the different carousel components. We have a global mock for useRouteNavigation in testSetup.ts which replaces it with a function that does nothing. You can override that in OnboardingCarousel.test.tsx with:

```
jest.mock('../../utils/hooks', () => ({
  ...jest.requireActual('../../utils/hooks'),
}))
```

That will place the original implementation back so navigation happens and the test succeeds.

2024-01-03 20:23 UTC, cadibemma commented on VAMobile/src/screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory.tsx
> +    return navigation.navigate('PrescriptionDetails', { prescriptionId: prescriptionID })
Thank you! It fixed the test

2024-01-04 18:13 UTC, alexandec submitted a review, later dismissed

2024-01-04 18:14 UTC, alexandec commented
Looks good!

2024-01-04 21:54 UTC, TKDickson commented
Two questions for you @cadibemma:

- Claims and Generic Letter were intentionally _not_ enabled for availability framework, can you check with @dumathane about adding them? It's not clear to me whether, with the rest of the changes in here, we'll be able to intentionally exclude them still. If not, there's probably other stuff we need to add to this change.
- Can you update the testing scope in the ticket? Seems like it's "retest Use Case 1 for all existing screens" (which is what was in there originally) and also "do initial AF testing for the ~9 screens where it's now enabled" and.... idk, maybe more. You've got a lot of changes here :)

2024-01-12 21:33 UTC, TKDickson approved these changes
QA approves merging to develop

2024-01-12 21:34 UTC, dumathane approved these changes

2024-01-12 22:56 UTC, merged