updated typescript to 4.9.5 before flipping to 5.0.0
department-of-veterans-affairs/va-mobile-app pull request #7709
Opened 2024-01-16 16:24 UTC by Sparowhawk

## Description of Change

## Screenshots/Video

## Testing

- [ ] Tested on iOS 
- [ ] Tested on Android 

## Reviewer Validations

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2024-01-17 21:35 UTC, alexandec requested changes
A couple minor changes

2024-01-17 21:58 UTC, Sparowhawk commented on VAMobile/src/App.tsx
> +type StackNaveParamList = WebviewStackParams & {
updated

2024-01-17 21:59 UTC, Sparowhawk commented on VAMobile/src/utils/hooks/index.tsx
> +          name: `${String(routeName)}`,
I did try that one and it wasn't working, not sure why, but I kept it the same as how the waygate does things cause I knew that worked.

2024-01-17 22:09 UTC, alexandec approved these changes

2024-01-22 19:00 UTC, alexandec submitted a review, later dismissed

2024-01-23 13:51 UTC, rbontrager submitted a review, later dismissed

2024-01-23 14:56 UTC, alexandec approved these changes

2024-01-23 15:44 UTC, merged

2024-01-23 16:30 UTC, rbontrager approved these changes