bug/7648-Chika-RemoveA11yLabelForEditAddress
department-of-veterans-affairs/va-mobile-app pull request #7886
Opened 2024-02-01 23:42 UTC by cadibemma

## Description of Change

- Removed a11y label for edit address

## Screenshots/Video

## Testing

- [ ] Tested on iOS 
- [ ] Tested on Android 

## Reviewer Validations

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2024-02-02 15:22 UTC, Sparowhawk approved these changes

2024-02-02 18:35 UTC, TKDickson requested changes
Something about this change has broken the button functionality - just for iOS. See explanation in ticket.

2024-02-05 16:51 UTC, dumathane approved these changes

2024-02-05 16:51 UTC, dumathane commented
FYI @cadibemma @TKDickson I tested on my personal device and can't reproduce the problem (And the code change shouldn't as far as I can tell make that problem occur so...maybe weird build issue Therese? Let me know.)

2024-02-05 21:01 UTC, TKDickson approved these changes
Approved for merge to dev

2024-02-05 23:04 UTC, merged