bug/9209-InAppRecruitmentSRIssue
department-of-veterans-affairs/va-mobile-app pull request #9212
Opened 2024-07-29 19:45 UTC by dumathane

## Description of Change

## Screenshots/Video

## Testing

- [ ] Tested on iOS 
- [ ] Tested on Android 

## Reviewer Validations

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2024-07-29 22:57 UTC, theodur requested changes

2024-07-29 22:57 UTC, theodur commented on VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/InAppRecruitmentScreen/InAppRecruitmentScreen.tsx
> +              a11yLabel: t('inAppRecruitment.makeAppBetter.bullet.1'),
We don't need the a11y label since it's the same as the text

2024-07-29 22:57 UTC, theodur commented on VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/InAppRecruitmentScreen/InAppRecruitmentScreen.tsx
> +              a11yLabel: t('inAppRecruitment.makeAppBetter.bullet.2'),
Same here

2024-07-30 17:03 UTC, theodur approved these changes

2024-07-30 17:37 UTC, TKDickson approved these changes
approved to merge to develop

2024-07-30 17:48 UTC, merged