Bug/9236-Binny-DisRatingSRFix
department-of-veterans-affairs/va-mobile-app pull request #9290
Opened 2024-08-07 21:21 UTC by dumathane

## Description of Change

## Screenshots/Video

## Testing

- [ ] Tested on iOS 
- [ ] Tested on Android 

## Reviewer Validations

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2024-08-08 19:22 UTC, cadibemma approved these changes

2024-08-08 19:33 UTC, theodur approved these changes

2024-08-09 15:49 UTC, TKDickson approved these changes
Approved to merge to develop

2024-08-09 15:57 UTC, TKDickson requested changes
JK, there's a merge conflict. Resolve that, I'll quickly test the in-app review, and then we can be good to go

2024-08-09 19:23 UTC, TKDickson approved these changes
ok good to go, now

2024-08-09 21:10 UTC, merged