finished
department-of-veterans-affairs/va-mobile-app pull request #9496
Opened 2024-08-28 18:56 UTC by Sparowhawk

## Description of Change
Updated the why we combine text on the large panel to read “Why we sometimes combine claims”

## Screenshots/Video
Before:

https://github.com/user-attachments/assets/b4293157-5e82-49f2-b2c8-bde98c61b706

After:

https://github.com/user-attachments/assets/28bbaa41-8ffe-4444-a157-4514b430649b

## Testing
yarn test

- [x] Tested on iOS 
- [x] Tested on Android 

## Reviewer Validations
Update the header for the screenreader to just recite: “Why we sometimes combine claims”.

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [x] PR is connected to issue(s)
- [x] Tests are included to cover this change (when possible)
- [x] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [x] No secrets or API keys are checked in
- [x] All imports are absolute (no relative imports)
- [x] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2024-08-28 20:10 UTC, alexandec approved these changes

2024-09-04 16:38 UTC, Sparowhawk commented
<img width="474" alt="Screenshot 2024-09-04 at 11 37 14 AM" src="https://github.com/user-attachments/assets/f8d3e3fc-6182-4933-ac97-48c2aef8652e">
<img width="474" alt="Screenshot 2024-09-04 at 11 37 28 AM" src="https://github.com/user-attachments/assets/c3bb6a5f-361b-4867-b0a6-ce065f53f649">


Updated Panel copy

2024-09-05 23:12 UTC, alexandec approved these changes

2024-09-06 17:45 UTC, brea11y approved these changes

2024-09-09 14:44 UTC, brea11y approved these changes

2024-09-09 20:03 UTC, rbontrager requested changes
Detox tests need to be updated

2024-09-11 14:04 UTC, rbontrager approved these changes

2024-09-11 14:49 UTC, merged