Snackbar documentation
department-of-veterans-affairs/va-mobile-app pull request #9538
Opened 2024-09-04 19:07 UTC by jessicawoodin

## Description of Change

- Updated Snackbar documentation in Flagship Design Library
- Added Snackbar documentation to Design System

## Screenshots/Video

## Testing

- [ ] Tested on iOS 
- [ ] Tested on Android 

## Reviewer Validations

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2024-09-04 21:38 UTC, TimRoe commented on VAMobile/documentation/design/Components/Alerts and progress/Snackbar.md
> +- Use `Dismiss` for right action button.
As coded, impossible to do otherwise.

2024-09-04 21:40 UTC, TimRoe commented on VAMobile/documentation/design/Components/Alerts and progress/Snackbar.md
> +- Screen readers should automatically focus/announce when a snackbar opens and begin reading its content. The screen reader will announce the component as an Alert as soon as the action is completed.
```suggestion
- Screen readers should automatically announce when a snackbar opens and begin reading its content. The screen reader will announce the component as an Alert as soon as the action is completed. Each action will be announced as a button.
```

2024-09-04 21:40 UTC, TimRoe commented on VAMobile/documentation/design/Components/Alerts and progress/Snackbar.md
> +- There should only ever be one snackbar on the screen. Opening a new snackbar will close the previous snackbar.
Part of the component, impossible to do otherwise.

2024-09-04 21:42 UTC, TimRoe commented on VAMobile/documentation/design/Components/Alerts and progress/Snackbar.md
> +- The current iteration of the snackbar will only be dismissible by the user selecting the “Dismiss” button, another snackbar opening, or the user navigating to a different screen. Additional iterati
Not sure if it falls here or below in the accessibility, but we do auto-dismiss non-actionable (no Undo/Try again) Snackbars after 5 seconds if the screen reader is on per discussion with Brea

2024-09-04 21:45 UTC, TimRoe commented on VAMobile/documentation/design/Components/Alerts and progress/Snackbar.md
> +- To ensure that the snackbar and its content is accessible to all users, the snackbar should not close on its own or after a certain amount of time. The snackbar can only be closed by the user selec
As commented above, closes after 5 seconds with screen reader enabled if no action.

> the snackbar should not close on its own or after a certain amount of time

Technically, it does close now after ~23 minutes due to the weird bit breaking with unit tests. Not sure we need to call that out in the design doc, but wanted to make sure it was known.

2024-09-04 21:47 UTC, TimRoe requested changes
Dropping request changes to indicate I read it and had suggested changes. Since it's design doc, can approve without them if you think it's fine as is.

2024-09-05 15:56 UTC, TimRoe approved these changes

2024-09-05 19:58 UTC, narin approved these changes

2024-09-05 20:02 UTC, merged