finished
department-of-veterans-affairs/va-mobile-app pull request #9539
Opened 2024-09-04 19:34 UTC by Sparowhawk

## Description of Change
Updated 2 accessibility hint copies in the file request flow and removed the duplicate header in the file request details screen

## Screenshots/Video
Toggle: <details><summary>Before/after:</summary><img src="https://github.com/user-attachments/assets/c8d036ac-0a22-4f6d-9b0d-836202c957f8" width="49%" />&nbsp;&nbsp;<img src="https://github.com/user-attachments/assets/707f5538-c8ee-481b-b655-4d360a10d524" width="49%" /></details>

## Testing
yarn test

- [x] Tested on iOS 
- [x] Tested on Android 

## Reviewer Validations
 On the file upload screen, the headings are duplicated. I would remove the one within the card / box or change one of them to be unique / different so they are not duplicates.
Examples of duplicate headings
 Claim screen > Alert > "Review file requests" button. The screenreader only copy says "Navigates you to the find upload page". I would update this to "Navigates you to the file requests screen (or page)".
 File requests > [items that need additional information / files]. The screenreader only copy says "Go to the file request details page to upload file". I would update this to "Navigates you to the file upload screen (or page)".

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [x] PR is connected to issue(s)
- [x] Tests are included to cover this change (when possible)
- [x] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [x] No secrets or API keys are checked in
- [x] All imports are absolute (no relative imports)
- [x] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2024-09-09 21:56 UTC, alexandec submitted a review, later dismissed

2024-09-18 14:50 UTC, alexandec approved these changes

2024-09-20 17:23 UTC, brea11y requested changes
Remove "or page" from the label. I included it in the original ticket as an option and assumed someone from the H&B team would make the final call on which word to use (screen or page). We typically use screen throughout the app, so I'd just keep using that for consistency. Sorry for any confusion!

2024-09-24 15:37 UTC, brea11y approved these changes
This sounds great! Thanks Dylan!

2024-09-24 15:59 UTC, alexandec approved these changes

2024-09-24 18:38 UTC, TKDickson approved these changes

2024-09-25 16:19 UTC, merged