bug/7837-updateRxAppHeadings
department-of-veterans-affairs/va-mobile-app pull request #9784
Opened 2024-10-03 22:14 UTC by alexandec

## Description of Change

Add header role to RX headings where it was missing.

## Screenshots/Video

Prescription details before:

https://github.com/user-attachments/assets/95c68a8a-06bd-4840-afc9-6628fe64b209

Prescription details after:

https://github.com/user-attachments/assets/41a57d06-a269-4325-b273-f92605ea5b3e

## Testing

- [ ] Tested on iOS 
- [ ] Tested on Android 

## Reviewer Validations

See ticket for full list of changes requested. I also added a comment there with additional info.

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [ ] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2024-10-04 16:02 UTC, Sparowhawk requested changes
I think the unit tests should be updated to match the new headers

2024-10-07 22:40 UTC, alexandec commented
@Sparowhawk I've updated and improved the unit tests this PR touches

2024-10-09 13:43 UTC, Sparowhawk approved these changes

2024-10-17 22:22 UTC, DJUltraTom approved these changes

2024-10-17 22:30 UTC, merged