Feature/9763 update medication wording for va video
department-of-veterans-affairs/va-mobile-app pull request #9888
Opened 2024-10-15 19:04 UTC by juancstlm-a6

## Description of Change
Update the content in appointment details for the listed types to include the following component when  `Upcoming` and `Cancelled` status. Existing content/wording relating to medication wording will be removed in favor of only the component listed below. 
- Video Atlas
- Video GFE
- Video Home

## Screenshots/Video

https://github.com/user-attachments/assets/d9fd6e90-e832-4b66-af64-62edabbd0c0e

## Testing

- [X] Tested on iOS 
- [X] Tested on Android 

## Reviewer Validations
- [ ] Update Video Atlas Appointment details to include the "Medication wording" component for `Upcoming` and `Cancelled` status
- [ ] Update GFE Appointment details to include the "Medication wording" component `Upcoming` and `Cancelled` status
- [ ] Update Video Home Appointment details to include the "Medication wording" component `Upcoming` and `Cancelled` status
- [ ] "Medication wording" component contains a link that opens https://www.va.gov/resources/what-should-i-bring-to-my-health-care-appointments/ in a in app web view
- [ ] "Medication wording" component contains a link that opens a Large Panel with details about appointments help

## PR Checklist

  **Reviewer:** Confirm the items below as you review

- [ ] PR is connected to issue(s)
- [X] Tests are included to cover this change (when possible)
- [ ] No magic strings (All string unions follow the [Union -> Constant](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/constants/common.ts) type pattern)
- [ ] No secrets or API keys are checked in
- [ ] All imports are absolute (no relative imports)
- [ ] New functions and Redux work have proper TSDoc annotations

## For QA

[Run a build for this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml)

2024-10-17 23:55 UTC, juancstlm-a6 commented on VAMobile/e2e/tests/AppointmentsExpanded.e2e.ts
> -      await element(by.text('Close')).tap()
This check is now part of checkMedicationWording

2024-10-17 23:56 UTC, juancstlm-a6 commented on VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/PrepareForVideoVisit/PrepareForVideoVisit.test.tsx
> -    ).toBeTruthy()
Figured since most of this was changing I should update this test to use only the translation function

2024-10-23 15:28 UTC, Sparowhawk requested changes
just the typo, but everything else seems good

2024-10-23 15:28 UTC, Sparowhawk commented on VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentMedicationWording.tsx
> +      const conent = getContent()
there is a typo here

2024-10-23 15:35 UTC, juancstlm-a6 commented on VAMobile/src/screens/HealthScreen/Appointments/AppointmentTypeComponents/SharedComponents/AppointmentMedicationWording.tsx
> +      const conent = getContent()
Doh! Updated

2024-10-23 17:05 UTC, mistymg commented
Posting what I had in Slack here, too:

1. I noticed the iOS screenshot includes some additional wording in the 3rd bullet ("or the link that's in your confirmation email") that the Android screenshot doesn't have. Which is correct? (Videos seemed ok though.)
2. Wondering about your choice to include a loading component for when user goes to web view.
-If a loading component is necessary, I'd suggest more explicit wording like Loading [VA.gov](http://va.gov/) webpage.... The 3 periods are necessary.

2024-10-23 17:45 UTC, Sparowhawk approved these changes
all good from what I can tell, just Misty's question left about loading message for the webview is all I think needs to be addressed

2024-10-23 17:57 UTC, juancstlm-a6 commented
Updated outdated screenshot for iOS
- Updated loading copy to "Loading VA.gov webpage..."
![Screenshot 2024-10-23 at 10 23 21 AM](https://github.com/user-attachments/assets/f1eea8a1-11d7-434f-9171-510dc25933a6)

https://github.com/user-attachments/assets/066d1d92-7fbc-4c8c-b02f-106698de8ccd

2024-10-24 18:40 UTC, Sparowhawk approved these changes

2024-10-25 16:10 UTC, TKDickson approved these changes

2024-10-25 16:18 UTC, merged